POST http://localhost:8080/student/mvc/student
Content-Type: application/json

< ./test.json

###

GET http://localhost:8080/student/mvc/student/params/500?comment=test comment
###

GET http://localhost:8080/student/mvc/student/params2/10/20
###
// ???  :-(   ???
// HTTP Status 400 – Bad Request
//GET http://localhost:8080/student/mvc/student/params2/0
//GET http://localhost:8080/student/mvc/student/params2/0/
//GET http://localhost:8080/student/mvc/student/params2/0/a
###

